spring.application.name=springboot
spring.mvc.apiversion.use.header=Api-Version
#debug=true
#server.port=8081
#Commented out these upper two overridden key:value,as they also are not needed for now

#COLORFUL CONSOLE & PROPER LOG PATTERN
logging.pattern.console=%clr(%d{yyyy-MM-dd HH:mm:ss}){white} %clr(%-5level){red} %clr([%thread]){cyan} --- %clr(%logger{36}){yellow} : %clr(%msg%n){green}

