package com.spring.springboot.p14_BackendValidation_RequestBodyValidation;

import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;

import java.io.Serializable;

public record UserDto(

        // No validation because id is usually generated by DB.
        Long id,

        /*
         * @NotBlank
         * - Username cannot be null.
         * - Username cannot be empty ("").
         * - Username cannot contain only spaces ("   ").
         *
         * Without this:
         * - Users could submit blank usernames.
         *
         * @Size(min = 2, max = 50)
         * - Username length must be between 2 and 50 characters.
         *
         * Without this:
         * - Very short names like "A" would be accepted.
         * - Very long usernames would also be accepted.
         */
        @NotBlank(message="Username cannot be blank, kindly enter your username")
        @Size(min = 2, max = 50, message="username cannot be more than 50 characters")
        String userName,

        /*
         * @NotBlank
         * - Email cannot be null, empty, or only spaces.
         *
         * @Email
         * - Email must follow a valid email format.
         *
         * Without @Email:
         * - Values like "abc", "hello123", "gmail.com"
         *   would be accepted as emails.
         */
        @NotBlank(message = "Email must not be blank, kindly Enter your valid Email")
        @Email(message = "Invalid email format , Kindly ensure entering correct email format")
        String email,

        /*
         * Message is optional because @NotBlank is not used.
         *
         * @Size(max = 100)
         * - If message is provided, it must not exceed 100 characters.
         *
         * Without this:
         * - Users could submit excessively long messages.
         */
        @Size(max = 100, message = "Message limit exceeded, message cannot be more then 100 characters")
        String message
) implements Serializable {
}